---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (^static/|^staticfiles/|^manage.py|^setup.py|^instance|^whiteboard/static)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-docstring-first
    - id: check-added-large-files
      args: ['--maxkb=1024']
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: trailing-whitespace
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: pretty-format-json
      args: ["--autofix", "--indent=2", "--no-sort-keys"]

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: python -m isort
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: python -m flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: python -m mypy
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: python -m pytest
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: python -m pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false

...
